#include <iostream>
#include <vector>
#include <string>
#include <memory>
#include <cstdint>
#include <algorithm>

#include "convolution.h"

// stb_image: load/save LDR images
#define STB_IMAGE_IMPLEMENTATION
#include "../external/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../external/stb_image_write.h"

#ifdef USE_VULKAN
#include "vk_utils.h"
#include "convolution_generated.h"  // generated by kernel_slicer
#endif

// -----------------------------------------------------------------------
// LDR (uint8) -> HDR (float, linear)
// -----------------------------------------------------------------------
static void ldrToHdr(const uint8_t* ldr, float* hdr, int w, int h, int channels)
{
  for (int i = 0; i < w * h; ++i)
  {
    hdr[4 * i + 0] = (channels > 0) ? ldr[channels * i + 0] / 255.0f : 0.0f;
    hdr[4 * i + 1] = (channels > 1) ? ldr[channels * i + 1] / 255.0f : 0.0f;
    hdr[4 * i + 2] = (channels > 2) ? ldr[channels * i + 2] / 255.0f : 0.0f;
    hdr[4 * i + 3] = (channels > 3) ? ldr[channels * i + 3] / 255.0f : 1.0f;
  }
}

// -----------------------------------------------------------------------
// HDR (float, linear) -> LDR (uint8, clamped)
// -----------------------------------------------------------------------
static void hdrToLdr(const float* hdr, uint8_t* ldr, int w, int h)
{
  for (int i = 0; i < w * h; ++i)
  {
    ldr[4 * i + 0] = (uint8_t)std::min(std::max(hdr[4 * i + 0] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 1] = (uint8_t)std::min(std::max(hdr[4 * i + 1] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 2] = (uint8_t)std::min(std::max(hdr[4 * i + 2] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 3] = (uint8_t)std::min(std::max(hdr[4 * i + 3] * 255.0f, 0.0f), 255.0f);
  }
}

// -----------------------------------------------------------------------
// Run convolution with a given impl and save result
// -----------------------------------------------------------------------
static void runAndSave(std::shared_ptr<Convolution2D> pImpl,
                       int w, int h,
                       const std::vector<float>& hdrIn,
                       const char* outPath)
{
  std::vector<float>   hdrOut(w * h * 4, 0.0f);
  std::vector<uint8_t> ldrOut(w * h * 4, 0);

  pImpl->CommitDeviceData();
  pImpl->Apply(w, h, hdrIn.data(), hdrOut.data());

  float timing[4] = {};
  pImpl->GetExecutionTime("Apply", timing);
  std::cout << "  time = " << timing[0] << " ms" << std::endl;

  hdrToLdr(hdrOut.data(), ldrOut.data(), w, h);
  stbi_write_png(outPath, w, h, 4, ldrOut.data(), w * 4);
  std::cout << "  saved -> " << outPath << std::endl;
}

// -----------------------------------------------------------------------
int main(int argc, char** argv)
{
  bool onGPU = false;
  for (int i = 1; i < argc; ++i)
    if (std::string(argv[i]) == "--gpu")
      onGPU = true;

  // Load LDR source image
  const char* imagePath = "../data/texture1.bmp";
  int w = 0, h = 0, channels = 0;
  uint8_t* ldrRaw = stbi_load(imagePath, &w, &h, &channels, 0);
  if (!ldrRaw)
  {
    std::cerr << "ERROR: cannot load image: " << imagePath << std::endl;
    return 1;
  }
  std::cout << "Loaded: " << imagePath << "  " << w << "x" << h
            << "  channels=" << channels << std::endl;

  // Convert LDR -> HDR
  std::vector<float> hdrData(w * h * 4);
  ldrToHdr(ldrRaw, hdrData.data(), w, h, channels);
  stbi_image_free(ldrRaw);

  // ------------------------------------------------------------------
  // Helper lambda: build impl, setup kernel, run, save
  // ------------------------------------------------------------------
  auto runKernel = [&](const std::string& name,
                       const std::string& suffix,
                       auto setupFn)
  {
    std::cout << "\n[" << name << "]" << std::endl;
    std::shared_ptr<Convolution2D> pImpl;

#ifdef USE_VULKAN
    if (onGPU)
    {
      auto ctx = vk_utils::globalContextGet(false, 0);
      pImpl = CreateConvolution2D_Generated(ctx, w * h);
    }
    else
#endif
      pImpl = std::make_shared<Convolution2D>();

    setupFn(pImpl);

    std::string outName = onGPU ? ("out_gpu_" + suffix + ".png")
                                : ("out_cpu_" + suffix + ".png");
    runAndSave(pImpl, w, h, hdrData, outName.c_str());
  };

  // Run several convolution types
  runKernel("Box Blur (radius=2)", "blur",
    [](std::shared_ptr<Convolution2D> p){ p->SetupBlurKernel(2); });

  runKernel("Gaussian Blur (radius=2, sigma=1.0)", "gaussian",
    [](std::shared_ptr<Convolution2D> p){ p->SetupGaussianBlurKernel(2, 1.0f); });

  runKernel("Sharpen", "sharpen",
    [](std::shared_ptr<Convolution2D> p){ p->SetupSharpenKernel(); });

  runKernel("Edge Detect (Laplacian)", "edges",
    [](std::shared_ptr<Convolution2D> p){ p->SetupEdgeDetectKernel(); });

  runKernel("Emboss", "emboss",
    [](std::shared_ptr<Convolution2D> p){ p->SetupEmbossKernel(); });

  // Canonical single-output files for CPU / GPU
  {
    std::cout << "\n[Gaussian Blur -> canonical output]" << std::endl;
    std::shared_ptr<Convolution2D> pImpl;
#ifdef USE_VULKAN
    if (onGPU)
    {
      auto ctx = vk_utils::globalContextGet(false, 0);
      pImpl = CreateConvolution2D_Generated(ctx, w * h);
    }
    else
#endif
      pImpl = std::make_shared<Convolution2D>();

    pImpl->SetupGaussianBlurKernel(2, 1.0f);
    const char* outPath = onGPU ? "out_gpu.png" : "out_cpu.png";
    runAndSave(pImpl, w, h, hdrData, outPath);
  }

  return 0;
}
