#include <iostream>
#include <vector>
#include <string>
#include <memory>
#include <cstdint>
#include <algorithm>

#include "convolution.h"

// stb_image: load/save LDR images
#define STB_IMAGE_IMPLEMENTATION
#include "../external/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../external/stb_image_write.h"

#ifdef USE_VULKAN
#include "vk_utils.h"
#include "convolution_generated.h"  // generated by kernel_slicer
#endif

#ifdef USE_VULKAN
std::shared_ptr<Convolution2D> CreateConvolution2D_Generated(vk_utils::VulkanContext a_ctx, size_t a_maxThreadsGenerated);
#endif

// -----------------------------------------------------------------------
// LDR (uint8) -> HDR (float, linear)
// -----------------------------------------------------------------------
static void ldrToHdr(const uint8_t* ldr, float* hdr, int w, int h, int channels)
{
  for (int i = 0; i < w * h; ++i)
  {
    hdr[4 * i + 0] = (channels > 0) ? ldr[channels * i + 0] / 255.0f : 0.0f;
    hdr[4 * i + 1] = (channels > 1) ? ldr[channels * i + 1] / 255.0f : 0.0f;
    hdr[4 * i + 2] = (channels > 2) ? ldr[channels * i + 2] / 255.0f : 0.0f;
    hdr[4 * i + 3] = 1.0f; // always fully opaque in HDR source
  }
}

// -----------------------------------------------------------------------
// HDR (float, linear) -> LDR (uint8, clamped), alpha always 255
// -----------------------------------------------------------------------
static void hdrToLdr(const float* hdr, uint8_t* ldr, int w, int h)
{
  for (int i = 0; i < w * h; ++i)
  {
    ldr[4 * i + 0] = (uint8_t)std::min(std::max(hdr[4 * i + 0] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 1] = (uint8_t)std::min(std::max(hdr[4 * i + 1] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 2] = (uint8_t)std::min(std::max(hdr[4 * i + 2] * 255.0f, 0.0f), 255.0f);
    ldr[4 * i + 3] = 255; // always fully opaque
  }
}

// -----------------------------------------------------------------------
int main(int argc, char** argv)
{
  bool onGPU = false;
  for (int i = 1; i < argc; ++i)
    if (std::string(argv[i]) == "--gpu")
      onGPU = true;

  // Load LDR source image
  const char* imagePath = "../data/texture1.bmp";
  int w = 0, h = 0, channels = 0;
  uint8_t* ldrRaw = stbi_load(imagePath, &w, &h, &channels, 0);
  if (!ldrRaw)
  {
    std::cerr << "ERROR: cannot load image: " << imagePath << std::endl;
    return 1;
  }
  std::cout << "Loaded: " << imagePath << "  " << w << "x" << h
            << "  channels=" << channels << std::endl;

  // Convert LDR -> HDR (alpha is forced to 1.0 in ldrToHdr)
  std::vector<float> hdrData(w * h * 4);
  ldrToHdr(ldrRaw, hdrData.data(), w, h, channels);
  stbi_image_free(ldrRaw);

  // Create pImpl once and reuse for all filters
  std::shared_ptr<Convolution2D> pImpl;
#ifdef USE_VULKAN
  if (onGPU)
  {
    auto ctx = vk_utils::globalContextGet(false, 0);
    pImpl = CreateConvolution2D_Generated(ctx, w * h);
  }
  else
#endif
    pImpl = std::make_shared<Convolution2D>();

  std::vector<float>   hdrOut(w * h * 4, 0.0f);
  std::vector<uint8_t> ldrOut(w * h * 4, 0);

  // Apply current filter state and save result.
  // Named "runFilter" to avoid confusion with GPU/kernel_slicer kernels.
  auto runFilter = [&](const std::string& name, const std::string& suffix)
  {
    std::cout << "\n[" << name << "]" << std::endl;

    // CommitDeviceData uploads updated m_kernel/m_kw/m_kh to GPU.
    // On CPU this is a no-op.
    pImpl->CommitDeviceData();

    pImpl->Apply(w, h, hdrData.data(), hdrOut.data());

    float timing[4] = {};
    pImpl->GetExecutionTime("Apply", timing);
    std::cout << "  time (exec) = " << timing[0] << " ms" << std::endl;
    std::cout << "  time (copy) = " << timing[1] + timing[2] << " ms" << std::endl;
    std::cout << "  time (ovrh) = " << timing[3] << " ms" << std::endl;

    hdrToLdr(hdrOut.data(), ldrOut.data(), w, h);

    std::string outName = onGPU ? ("out_gpu_" + suffix + ".png")
                                : ("out_cpu_" + suffix + ".png");
    stbi_write_png(outName.c_str(), w, h, 4, ldrOut.data(), w * 4);
    std::cout << "  saved -> " << outName << std::endl;
  };

  pImpl->SetupBlurKernel(2);
  runFilter("Box Blur (radius=2)", "blur");

  pImpl->SetupGaussianBlurKernel(2, 1.0f);
  runFilter("Gaussian Blur (radius=2, sigma=1.0)", "gaussian");

  pImpl->SetupSharpenKernel();
  runFilter("Sharpen", "sharpen");

  pImpl->SetupEdgeDetectKernel();
  runFilter("Edge Detect (Laplacian)", "edges");

  pImpl->SetupEmbossKernel();
  runFilter("Emboss", "emboss");

  // The last filter run also serves as the canonical out_cpu/out_gpu output.
  // Here we re-use the already-saved emboss result and just make a copy
  // with the canonical name so the caller always gets out_cpu.png / out_gpu.png.
  const char* outPath = onGPU ? "out_gpu.png" : "out_cpu.png";
  stbi_write_png(outPath, w, h, 4, ldrOut.data(), w * 4);
  std::cout << "\nCanonical output (emboss) saved -> " << outPath << std::endl;

  return 0;
}
